services:
  # ==========================================
  # 1. DB AND RABBITMQ
  # ==========================================
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    networks:
      - uber-eats-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - uber-eats-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - uber-eats-network

  # ==========================================
  # 2. DISCOVERY & GATEWAY
  # ==========================================
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: eureka-server
    env_file:
      - .env
    ports:
      - "8761:8761"
    networks:
      - uber-eats-network

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  # ==========================================
  # 3. BUSINESS-MICROSERVICES
  # ==========================================
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-service
    env_file:
      - .env
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: restaurant-service
    env_file:
      - .env
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: payment-service
    env_file:
      - .env
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: delivery-service
    env_file:
      - .env
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/delivery_db?authSource=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: notification-service
    env_file:
      - .env
    ports:
      - "8085:8085"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      rabbitmq:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - uber-eats-network

networks:
  uber-eats-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  mongodb_data: