CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE accounts (
                          account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          surname VARCHAR(255),
                          login VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          email VARCHAR(255) UNIQUE,
                          phone VARCHAR(255),
                          created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE account_roles (
                               account_id BIGINT NOT NULL,
                               role_id BIGINT NOT NULL,
                               PRIMARY KEY (account_id, role_id),
                               CONSTRAINT fk_account_roles_account_id
                                   FOREIGN KEY (account_id) REFERENCES accounts (account_id) ON DELETE CASCADE,
                               CONSTRAINT fk_account_roles_role_id
                                   FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);