CREATE TABLE restaurants (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             address VARCHAR(255),
                             email VARCHAR(255),
                             image_url VARCHAR(255),
                             is_active BOOLEAN DEFAULT true,
                             phone VARCHAR(255),
                             created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE menu_categories (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(255) NOT NULL,
                                 image_url VARCHAR(255),
                                 restaurant_id BIGINT NOT NULL,
                                 CONSTRAINT fk_category_restaurant
                                     FOREIGN KEY (restaurant_id)
                                         REFERENCES restaurants (id)
                                         ON DELETE CASCADE
);

CREATE TABLE menu_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            category_id BIGINT NOT NULL,
                            name VARCHAR(255) NOT NULL,
                            description VARCHAR(255),
                            price NUMERIC(38, 2) NOT NULL,
                            image_url VARCHAR(255),
                            is_available BOOLEAN DEFAULT true,
                            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_item_category
                                FOREIGN KEY (category_id)
                                    REFERENCES menu_categories (id)
                                    ON DELETE CASCADE
);

CREATE TABLE restaurants_order (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   restaurant_id BIGINT NOT NULL,
                                   order_id BIGINT NOT NULL,
                                   order_status VARCHAR(255) NOT NULL,
                                   created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                   CONSTRAINT fk_restaurant_order
                                       FOREIGN KEY (restaurant_id)
                                           REFERENCES restaurants (id)
                                           ON DELETE CASCADE
);

CREATE TABLE outbox_event (
                              id UUID PRIMARY KEY,
                              aggregate_type VARCHAR(255) NOT NULL,
                              aggregate_id VARCHAR(255) NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              payload JSONB NOT NULL,
                              status VARCHAR(50) NOT NULL,
                              retry_count INTEGER NOT NULL DEFAULT 0,
                              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              processed_at TIMESTAMP WITH TIME ZONE
);