CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          restaurant_id BIGINT NOT NULL,
                          order_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          total_price DECIMAL(10, 2) NOT NULL,
                          payment_status VARCHAR(50) NOT NULL,
                          transaction_id VARCHAR(255),
                          failure_reason VARCHAR(255),
                          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE outbox_event (
                              id UUID PRIMARY KEY,
                              aggregate_type VARCHAR(255) NOT NULL,
                              aggregate_id VARCHAR(255) NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              payload JSONB NOT NULL,
                              status VARCHAR(50) NOT NULL,
                              retry_count INTEGER NOT NULL DEFAULT 0,
                              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              processed_at TIMESTAMP WITH TIME ZONE
);