server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/