server:
  port: 8083

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/user_eats_clone_order
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  key: ${JWT_SECRET_KEY}

app:
  services:
    restaurant-holder:
      url: "http://localhost:8082"
