server:
  port: 8084

spring:
  application:
    name: delivery-service
  mongodb:
    uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/uber_eats_delivery?authSource=admin
  data:
    mongodb:
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/